# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore ProcessOverwatch.Controller/ProcessOverwatch.Controller.sln
    - name: Build Shared
      run: dotnet build ProcessOverwatch.Shared/ProcessOverwatch.Shared.csproj --no-restore
    - name: Build Agent
      run: dotnet build ProcessOverwatch.Agent/ProcessOverwatch.Agent.csproj --no-restore
    - name: Build Controller
      run: dotnet build ProcessOverwatch.Controller/ProcessOverwatch.Controller.csproj --no-restore
    - name: Test Shared
      run: dotnet test ProcessOverwatch.Shared/ProcessOverwatch.Shared.csproj --no-build --verbosity normal
    - name: Test Agent
      run: dotnet test ProcessOverwatch.Shared/ProcessOverwatch.Shared.csproj --no-build --verbosity normal
    - name: Test Controller
      run: dotnet test ProcessOverwatch.Controller/ProcessOverwatch.Controller.csproj --no-build --verbosity normal
